language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

before_script:
  - git checkout master
  - composer self-update && composer install

script: bin/kahlan --config=kahlan-config.travis.php

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover "scrutinizer.xml"
  - curl -F "json_file=@coveralls.json" https://coveralls.io/api/v1/jobs
